/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CPFIClient */

#ifndef _Included_CPFIClient
#define _Included_CPFIClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CPFIClient
 * Method:    BeforeSendReq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CPFIClient_BeforeSendReq
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
