/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_zookeeper_client_java_CPFIClient */

#ifndef _Included_org_apache_zookeeper_client_java_CPFIClient
#define _Included_org_apache_zookeeper_client_java_CPFIClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_zookeeper_client_java_CPFIClient
 * Method:    BeforeSendReq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_zookeeper_client_1java_CPFIClient_BeforeSendReq
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
